### ISSUE TITLE
Add client transaction rate limiter

### ISSUE THREAD

**Issue by thanethomson** [interchainio/tm-load-test#17]
For certain experiments we need a way to fix the number of generated transactions per second from the client.

In the `[clients]` section of the configuration file, we should have something like:

```toml
[clients]
# The number of interactions per second. Set to -1 to remove limiting.
interaction_rate = 100
```
